apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: gf-space
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - services
    - pods
    verbs:
    - get
    - watch
    - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
  namespace: gf-space
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: gf-space
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gf-space
  name: promtail-configmap
data:
  config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://loki:3100/loki/api/v1/push
    
    scrape_configs:
    - job_name: dnsmasq
      static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          app: snsmasq
          __path__: /var/log/dnsmasq/dnsmasq.log
          nodename: ${HOSTNAME}
    - job_name: system
      static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
          nodename: ${HOSTNAME}
      relabel_configs:
        - source_labels:
            - __meta_kubernetes_pod_node_name
          target_label: __host__
    - job_name: syslog
      static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/syslog
          nodename: ${HOSTNAME}
    - job_name: journal
      journal:
        max_age: 12h
        path: /var/log/journal
        labels:
          job: system-journal
      relabel_configs:
        - source_labels: ['__journal__systemd_unit']
          target_label: 'unit'
        - source_labels: ["__journal_priority_keyword"]
          target_label: level
        - source_labels:
          - __journal__hostname
          target_label: nodename
        - source_labels:
          - __journal_syslog_identifier
          target_label: syslog_identifier
    - job_name: pod-logs
      kubernetes_sd_configs:
        - role: pod
      pipeline_stages:
        - docker: {}
      relabel_configs:
        - source_labels:
            - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          replacement: $1
          separator: /
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_name
          target_label: job
        - source_labels:
            - __meta_kubernetes_pod_node_name
          target_label: nodename
        - action: replace
          source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
          target_label: __path__
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: gf-space
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9080'
        prometheus.io/path: /metrics
        podinfo: "各ノード内のPodや本体のデータ監視用のpromtail"
    spec:
      serviceAccountName: promtail
      serviceAccount: promtail
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: promtail
        # image: grafana/promtail:2.8.11
        image: grafana/promtail:2.9.13
        # image: grafana/promtail
        args:
        - --config.file=/etc/promtail/config.yaml
        - --config.expand-env=true
        # - --client.external-labels=hostname=${HOSTNAME}
        # - --config.file=/etc/promtail/config.yml
        env: 
        - name: 'HOSTNAME' # needed when using kubernetes_sd_configs
          valueFrom:
            fieldRef:
              fieldPath: 'spec.nodeName'
        ports:
        - containerPort: 9080
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 150m
            memory: 300Mi
        volumeMounts:
        - name: log
          mountPath: /var/log
        - name: journal-var
          mountPath: /var/log/journal
          readOnly: true
        - name: machine-id
          mountPath: /etc/machine-id
          readOnly: true
        - name: journal-run
          mountPath: /run/log/journal
          readOnly: true
        - name: config-vol
          mountPath: /etc/promtail/config.yaml
          subPath: config.yaml
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      volumes:
      - name: log
        hostPath:
          path: /var/log
      - hostPath:
          path: /var/log/journal
        name: journal-var
      - name: machine-id
        hostPath:
          path: /etc/machine-id
      - hostPath:
          path: /run/log/journal
        name: journal-run
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-vol
        configMap:
          name: promtail-configmap
          items:
            - key: config.yaml
              path: config.yaml
