---
apiVersion: v1
kind: Namespace
metadata:
  name: test-linkerd
  annotations:
    linkerd.io/inject: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-linkerd
  labels:
    mirror.linkerd.io/exported: "true"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-test
  namespace: test-linkerd
  labels:
    mirror.linkerd.io/exported: "true"
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP