apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k8s-worker-01
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm
                    - arm64
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.5
        ports:
        - containerPort: 9200
        resources:
          limits:
            memory: 15Gi
          requests:
            cpu: 2
            memory: 12Gi
        env:
          - name: "bootstrap.memory_lock"
            value: "true"
          - name:  "cluster.routing.allocation.disk.threshold_enabled"
            value: "false"
          - name: "discovery.type"
            value: "single-node"
          - name: "xpack.security.enabled"
            value: "false"
          - name: "xpack.monitoring.collection.enabled"
            value: "true"
          - name: ES_JAVA_OPTS
            value: "-Xms6000m -Xmx7500m"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data /usr/share/elasticsearch/plugins
        - sysctl -w vm.max_map_count=262144
        - chmod 777 /usr/share/elasticsearch/data /usr/share/elasticsearch/plugins
        - chomod 777 /usr/share/elasticsearch/data/node
        - chmod g+rwx /usr/share/elasticsearch/data /usr/share/elasticsearch/plugins
        - chgrp 1000 /usr/share/elasticsearch/data /usr/share/elasticsearch/plugins
        image: busybox:1.29.2
        imagePullPolicy: IfNotPresent
        name: set-dir-owner
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data
        - mountPath: /usr/share/elasticsearch/plugins
          name: es-p-data
      # - name: plugins-install
      #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.5
      #   command: ['sh', '-c']
      #   args:
      #   - |
      #     rm -rf /usr/share/elasticsearch/plugins/*; /usr/share/elasticsearch/bin/elasticsearch-plugin install http://10.0.0.1:1880/analysis-kuromoji-8.15.5.zip
      #   volumeMounts:
      #   - mountPath: /usr/share/elasticsearch/data
      #     name: es-data
      #   - name: es-p-data
      #     mountPath: /usr/share/elasticsearch/plugins
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: es-data
        hostPath:
          path: /usb-disk/usb1/nfs/es
        # persistentVolumeClaim:
        #   claimName: es-disk-claim
      - name: es-p-data
        hostPath:
          path: /usb-disk/usb1/nfs/es-plugins
        # persistentVolumeClaim:
        #   claimName: es-p-disk-claim
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
  #type: LoadBalancer
  type: ClusterIP
