apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-disk
  namespace: elasticsearch
spec:
  storageClassName: "elasticserach"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: k8s-worker-01
    path: /usb-disk/usb1/nfs/es

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-disk-claim
  namespace: elasticsearch
  labels:
    app: es-disk
spec:
  storageClassName: "elasticserach"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-p-disk
  namespace: elasticsearch
spec:
  storageClassName: "elasticserach-p"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: k8s-worker-01
    path: /usb-disk/usb1/nfs/es-plugins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-p-disk-claim
  namespace: elasticsearch
  labels:
    app: es-p-disk
spec:
  storageClassName: "elasticserach-p"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
