apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-disk
spec:
  storageClassName: "elasticserach"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: k8s-worker-01
    path: /usb-disk/usb1/nfs/es

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-disk-claim
  labels:
    app: es-disk
spec:
  storageClassName: "elasticserach"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi