apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metricbeat
  namespace: kube-system
  labels:
    app: metricbeat
spec:
  selector:
    matchLabels:
      name: metricbeat
  template:
    metadata:
      labels:
        name: metricbeat
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm
                    - arm64
      serviceAccountName: metricbeat
      serviceAccount: metricbeat
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:8.15.3
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
          "--system.hostfs=/hostfs",
        ]
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: KIBANA_HOST
          value: kibana:5601
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true
        - name: root
          mountPath: /hostfs
          readOnly: true
        - name: run
          mountPath: /var/run
          readOnly: true
        - name: metricbeat-config
          mountPath: /usr/share/metricbeat/metricbeat.yml
          subPath: metricbeat.yml

      terminationGracePeriodSeconds: 30
      hostNetwork: true
      hostPID: true

      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: root
        hostPath:
          path: /
      - name: run
        hostPath:
          path: /var/run
      - name: metricbeat-config
        configMap:
          name: metricbeat-cm
          items:
            - key: metricbeat.yml
              path: metricbeat.yml