apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-egent
  namespace: gf-space
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  ingress:
  - ports:
    - port: 9100
      protocol: TCP