apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gf-space
  name: loki-configmap
data:
  local-config.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
        
    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    ruler:
      alertmanager_url: http://localhost:9093

    limits_config:
      otlp_config:
        resource_attributes:
          ignore_defaults: false
          attributes_config:
            - action: index_label
              attributes:
              - service.name
              - process.runtime.name
              - service.version
              - host.name
              - detected.level
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: gf-space
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3100'
        prometheus.io/path: /metrics
        podinfo: "logを収集する Grafana Loki"
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/hostname
      #             operator: In
      #             values:
      #               - "k8s-worker-03"
      containers:
        - name: loki
          image: grafana/loki:3.2.1
          # image: grafana/loki:2.7.4
          imagePullPolicy: IfNotPresent
          args:
          - --config.file=/etc/loki/local-config.yaml       #   command: ["-config.file=/etc/loki/local-config.yaml"]
          ports:
            - containerPort: 3100
          resources:
            limits:
              cpu: 300m
              memory: 0.75Gi
            requests:
              cpu: 100m
              memory: 0.5Gi
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/local-config.yaml
              subPath: local-config.yaml
            - name: loki-vol
              mountPath: /loki
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 10001:10001 /loki
        - chmod 766 /loki
        - chmod g+rwx /loki
        image: busybox:1.29.2
        imagePullPolicy: IfNotPresent
        name: set-dir-owner
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /loki
          name: loki-vol
      volumes:
        - name: loki-vol
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-config
          configMap:
            name: loki-configmap
            items:
              - key: local-config.yaml
                path: local-config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: gf-space
spec:
  selector:
    app: loki
  ports:
    - port: 3100
  clusterIP: None
---