apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: example
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: 192.168.0.1
  peerPort: 179
  sourceAddress: 192.168.0.50
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: k8s-master-01