apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.80-192.168.0.99
  # autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-pool-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
  interfaces:
  - wlan0